<?php $__env->startSection('title','Manage Tests'); ?>
<?php $__env->startSection('content'); ?>
<div class="container-fluid"><div class="row"><?php echo $__env->make('admin.partials.sidebar', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
<div class="col-md-10 py-4 px-4"><?php if(session('success')): ?><div class="alert alert-success"><?php echo e(session('success')); ?></div><?php endif; ?>
<div class="d-flex justify-content-between align-items-center mb-4"><h4 class="mb-0">Manage Tests</h4><a href="<?php echo e(route('admin.tests.create')); ?>" class="btn btn-primary" style="background:#003366;border:none;"><i class="bi bi-plus-lg"></i> Create New Test</a></div>
<div class="card border-0 shadow-sm"><div class="card-body p-0"><table class="table table-hover mb-0"><thead class="table-light"><tr><th>ID</th><th>Title</th><th>Sections</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $tests; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $test): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><?php echo e($test->id); ?></td><td><a href="<?php echo e(route('admin.tests.show',$test)); ?>" class="fw-bold text-decoration-none"><?php echo e($test->title); ?></a></td><td><span class="badge bg-secondary"><?php echo e($test->sections_count); ?></span></td>
<td><form method="POST" action="<?php echo e(route('admin.tests.toggle',$test)); ?>" class="d-inline"><?php echo csrf_field(); ?><button type="submit" class="badge border-0 <?php echo e($test->is_active?'bg-success':'bg-danger'); ?>" style="cursor:pointer"><?php echo e($test->is_active?'Active':'Inactive'); ?></button></form></td>
<td><?php echo e($test->created_at->format('d M Y')); ?></td><td><a href="<?php echo e(route('admin.tests.show',$test)); ?>" class="btn btn-sm btn-outline-primary"><i class="bi bi-eye"></i></a> <a href="<?php echo e(route('admin.tests.edit',$test)); ?>" class="btn btn-sm btn-outline-warning"><i class="bi bi-pencil"></i></a> <form method="POST" action="<?php echo e(route('admin.tests.delete',$test)); ?>" class="d-inline" onsubmit="return confirm('Delete?')"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="6" class="text-center text-muted py-4">No tests yet.</td></tr><?php endif; ?></tbody></table></div></div></div></div></div>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('layouts.app', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH D:\ielts-mock-test\ielts-mock-test\resources\views/admin/tests/index.blade.php ENDPATH**/ ?>